package app;

import javax.swing.JOptionPane;


/**
 *
 * @author Aneeka
 */
public class dept extends javax.swing.JFrame {

    /**
     * Creates new form d3
     */
    public dept() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        gyn = new javax.swing.JRadioButton();
        eye = new javax.swing.JRadioButton();
        ent = new javax.swing.JRadioButton();
        ped = new javax.swing.JRadioButton();
        neur = new javax.swing.JRadioButton();
        card = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jButton1.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        jButton1.setText("Next");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(220, 300, 85, 37);

        gyn.setText(" Gynaecology");
        gyn.setContentAreaFilled(false);
        jPanel1.add(gyn);
        gyn.setBounds(340, 230, 160, 31);

        eye.setText(" Ophthalmology");
        eye.setContentAreaFilled(false);
        jPanel1.add(eye);
        eye.setBounds(340, 170, 180, 31);

        ent.setText(" Otorhinolaryngology");
        ent.setContentAreaFilled(false);
        jPanel1.add(ent);
        ent.setBounds(340, 110, 210, 31);

        ped.setText(" Pediatrics");
        ped.setContentAreaFilled(false);
        jPanel1.add(ped);
        ped.setBounds(50, 230, 170, 31);

        neur.setText(" Neurology");
        neur.setContentAreaFilled(false);
        jPanel1.add(neur);
        neur.setBounds(50, 170, 123, 31);

        card.setText(" Cardiology");
        card.setContentAreaFilled(false);
        jPanel1.add(card);
        card.setBounds(50, 110, 125, 31);

        jLabel3.setFont(new java.awt.Font("Kristen ITC", 1, 16)); // NOI18N
        jLabel3.setText(" Choose the department that you wish to make an appointment with");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(0, 40, 610, 23);

        jLabel2.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        jLabel2.setText("Welcome to MediNet!");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 0, 270, 28);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/v4.jpg"))); // NOI18N
        jLabel1.setIconTextGap(0);
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 610, 400);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 610, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 399, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        /*jRadioButton1.setActionCommand(jRadioButton1.getText());
        jRadioButton2.setActionCommand(jRadioButton2.getText());
        jRadioButton6.setActionCommand(jRadioButton6.getText());
        jRadioButton7.setActionCommand(jRadioButton7.getText());
        jRadioButton8.setActionCommand(jRadioButton8.getText());
        jRadioButton9.setActionCommand(jRadioButton9.getText());*/
        
        if(card.isSelected()){
           this.setVisible(false);
           String a="Welcome to Cardiology Department!";
           new apn(a).setVisible(true);
        }
        else if(neur.isSelected()){
           this.setVisible(false);
           String b="Welcome to Neurology Department!";
           new apn(b).setVisible(true);
        }
        else if(ped.isSelected()){
           this.setVisible(false);
           String c="Welcome to Pediatrics Department!";
           new apn(c).setVisible(true);
        }
         else if(ent.isSelected()){
           this.setVisible(false);
           String d="Welcome to Otorhinolaryngology Department!";
           new apn(d).setVisible(true);
        }
        else if(eye.isSelected()){
           this.setVisible(false);
           String e="Welcome to Ophthalmology Department!";
           new apn(e).setVisible(true);
        }
        else if(gyn.isSelected()){
           this.setVisible(false);
           String f="Welcome to Gynaecology Department!";
           new apn(f).setVisible(true);
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Please choose a department!");
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dept.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dept.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dept.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dept.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dept().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton card;
    private javax.swing.JRadioButton ent;
    private javax.swing.JRadioButton eye;
    private javax.swing.JRadioButton gyn;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton neur;
    private javax.swing.JRadioButton ped;
    // End of variables declaration//GEN-END:variables
}
